apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-proj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-kowshit
  template:
    metadata:
      labels:
        app: express-kowshit
    spec:
      containers:
        - name: express-mandar-container
          image: localhostnick/express-proj:01
